### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mooziii** [Obsilabor/obsi-bot#1]
# 📋 TODO

- [ ] giveaways
- [ ] polls
- [ ] complete english localization
- [ ] complete german localization
- [ ] command for changing guild settings
- [ ] help command

**Comment by mooziii** [comment]
poll percentage needs a fancy method to display correctly @polylymer mach das mal haha

**Comment by mooziii** [comment]
> poll percentage needs a fancy method to display correctly @polylymer mach das mal haha

did it [#322e345](https://github.com/mooziii/obsi-bot/commit/e6802e765689c309197428a9a627c3816a06afb6)

**Comment by polylymer** [comment]
Ja heute nicht mehr

**Comment by mooziii** [comment]
ja ahbs doch selbst geamcht lol
